language: node_js
node_js:
- '8'
- '10'
- node
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: Eqx10GiLDG0Cbxt+bxlxpDAxEiSCoFlp7fQ0rw28h1jW/9Q7NCbJHAJHm4+jGsk/CeJIExIdqeYqrqv/MzL3a4lQZufe0K8Y2KUB5WTZDtPzxvAFqbVnjVr/vPfG6MQ/M3Ke8V3dPL3x9pDljAhaEMSavCF4qcC7ulFmxleGnRRnejv9PnIu4M4ok2HIAL23aSE3b41yDkWQVR3erqpxKsl4cieEOyyG6lER+Z9OYUpHAlA71hvlRRWYdS1CLm4WNxdPkUa9T2miIRg0rjSLe2AjJ3UQUtEL19Ca2tG9LERM6WwtqvMRXMMpvtHlCzFAUfi9IZTneno7aksUWbxneKGV4AEW3/s7bOJJnFNBWwEPZXZIWOXOP1XDM0RR/74EBIr1FFAq66Imc9pj4/ZyK3/82HrDCOf9FAt0T6rHD4N2YO9OX2dq7glr6dt9rRCLdCMmOXgKSCNS81B8aXDkbILSyI8HI5P8kc70vPUcxcf2lAUZruDZ+c7hBDdBBg6cr3pLRaA0/3EmYyAhlOqCFxIamtb27uvDA69rMRllgZ5+aDySYDphEonQqtFklGq3SiPOy1GS3Gmmc0rpPksObdbEaEilHtdOdroNiLGU4rScCStjwjrekfbmqo4+lRCqT5zw+PvkXW+SFBWFNjIDYrsRtXwT8bqpNQN4W8Xqhz4=
  on:
    tags: true
    repo: xogroup/felicity
notifications:
  slack:
    secure: TBDxUfHiPNvuzFqFNWfqU4k2uVvhM5GtJzzQNpeezuOY5w3IJzcofA9a9wK/swXejzgtBbqXgwbt2AZJS/YJpsvcJsZa/VaVMUExx1dzHo/m26fTOHpBcV2vOHK2ThkUAIYwA3sdKhJa7h8rn2cKV18ttKBStb+4kJ3FoIus8miAihdiikOGKTdMFx+GPSksi7XtEpPNRyFZTPmTWhuidWSyhLFNKr7hUBJqzlEpJ/fZNXr+mboVOTlWcDyQ+Sul/fdiLiqsABVuA2t7Mn2Tp3JtVwZBUHPk6m4blviW2xYdRjTU4b7dxoRMXvXkYzTofcxY3j9VuP+N/ceqM0I0zx4lFrArZA8k+d0hXQmcrDU5kIPOznY/gtWkXeVElcpFPA9W2JkQw1icbHKpKly09Q4cWGmrEjXx/fwFA5cW4DXRFo71T3crlYBLtFFTCmKT+4ckUugUXL2MYZAuwbk8VqwTKGMNeL1FwhQxu9G/RtCXO5aH3HmQm51vS734f5O0Wukp+wvo4G9H1L7GbHLUs9gi0qVxOE4Wd3ploSUkevj6R58U34Qxft6u6+MyvcEYwQRX1/CvbtanIFWFynwXEJFCcFNqXMBeiV+jJG93qdHwz0TcJuIiNl7KXDvKsXZEOPIdV46YQ9GLtF8J3Pr2fFhfJ0f2ffYROLnFS+eL8Dg=
